# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: straightUp
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_intellllllface:
  joints:
    - first_to_second
    - second_to_third
    - third_to_forth
    - forth_to_fifth
  sim_control_mode: 1  # 0: position, 1: velocity

controller_list:
    - name: /reachAlpha/joint_1_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - first_to_second

    - name: /reachAlpha/joint_2_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - second_to_third

    - name: /reachAlpha/joint_3_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - third_to_forth

    - name: /reachAlpha/joint_4_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - forth_to_fifth

reachAlpha:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers --------------dobot-------------------------
    joint_1_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - first_to_second
      gains:
          first_to_second: {p: 200.0, i: 0.1, d: 0.9}
    joint_2_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - second_to_third
      gains:
          second_to_third: {p: 200.0, i: 0.1, d: 0.9}
    joint_3_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - third_to_forth
      gains:
          third_to_forth: {p: 200.0, i: 0.1, d: 0.9}
    joint_4_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - forth_to_fifth
      gains:
          forth_to_fifth: {p: 200.0, i: 0.1, d: 0.9}
