reachAlpha:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers --------------dobot-------------------------
    joint_1_controller:
      type: effort_controllers/JointPositionController
      joint: first_to_second
      pid: {p: 200.0, i: 0.1, d: 0.9}
    joint_2_controller:
      type: effort_controllers/JointPositionController
      joint: second_to_third
      pid: {p: 200.0, i: 0.1, d: 0.9}
    joint_3_controller:
      type: effort_controllers/JointPositionController
      joint: third_to_forth
      pid: {p: 200.0, i: 0.1, d: 0.9}
    joint_4_controller:
      type: effort_controllers/JointPositionController
      joint: forth_to_fifth
      pid: {p: 200.0, i: 0.1, d: 0.9}
