# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  first_to_second:
    has_velocity_limits: true
    max_velocity: 3.5
    has_acceleration_limits: false
    max_acceleration: 0
  forth_to_fifth:
    has_velocity_limits: true
    max_velocity: 3.5
    has_acceleration_limits: false
    max_acceleration: 0
  second_to_third:
    has_velocity_limits: true
    max_velocity: 3.5
    has_acceleration_limits: false
    max_acceleration: 0
  third_to_forth:
    has_velocity_limits: true
    max_velocity: 3.5
    has_acceleration_limits: false
    max_acceleration: 0